### PR TITLE
Change the way DOM added nodes are checked

### PR DESCRIPTION
**Pull request by nicomollet**
See the original ticket submitted to @verlok (https://github.com/verlok/lazyload/issues/339) 

I found a way to always load images after an ajax call (in my case: infinite scroll pagination), with mutation observer.
There was a bug making impossible to load the last page images.

By checking if the new nodes contain or are img tags, the new code works in any case.

Please check on your side too. 
Thank you.

### CODE REVIEW

**Comment by nicomollet** [comment]
Tests didn't pass :( if you can please make them work.

**Comment by nicomollet** [comment]
> Hey! You altered all the indentation from the original, so it’s now very difficult to see what’s changed. Could you please use the same indentation as the before-pr version, and commit again? Thanks

I have trouble fixing indentation for this javascript inside the PHP var. Hope @Tabrisrp can help on this.

**Comment by Tabrisrp** [comment]
Indentation for this project uses spaces instead of tabs  to follow PSR2 rules, so you need to take that into account.

**Comment by Tabrisrp** [comment]
I integrated your changes in #44

**Comment by nicomollet** [comment]
Thanks a lot @Tabrisrp

**Pull request closed without merging**
